# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bingo.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1587, 1083)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icona/icona.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.Catalan, QtCore.QLocale.Spain))
        MainWindow.setIconSize(QtCore.QSize(1080, 1080))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(89, 147, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.logo1 = QtWidgets.QLabel(self.centralwidget)
        self.logo1.setObjectName("logo1")
        self.horizontalLayout.addWidget(self.logo1)
        spacerItem1 = QtWidgets.QSpacerItem(88, 147, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.bingoSopar = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.bingoSopar.setFont(font)
        self.bingoSopar.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.bingoSopar.setAlignment(QtCore.Qt.AlignCenter)
        self.bingoSopar.setObjectName("bingoSopar")
        self.verticalLayout.addWidget(self.bingoSopar)
        self.esplai = QtWidgets.QLabel(self.centralwidget)
        self.esplai.setAlignment(QtCore.Qt.AlignCenter)
        self.esplai.setObjectName("esplai")
        self.verticalLayout.addWidget(self.esplai)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem4 = QtWidgets.QSpacerItem(89, 147, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.logo2 = QtWidgets.QLabel(self.centralwidget)
        self.logo2.setObjectName("logo2")
        self.horizontalLayout.addWidget(self.logo2)
        spacerItem5 = QtWidgets.QSpacerItem(88, 147, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 3)
        spacerItem6 = QtWidgets.QSpacerItem(20, 132, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem6, 1, 2, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.taulaNumeros = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.taulaNumeros.sizePolicy().hasHeightForWidth())
        self.taulaNumeros.setSizePolicy(sizePolicy)
        self.taulaNumeros.setMinimumSize(QtCore.QSize(1500, 386))
        self.taulaNumeros.setSizeIncrement(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.taulaNumeros.setFont(font)
        self.taulaNumeros.setFocusPolicy(QtCore.Qt.NoFocus)
        self.taulaNumeros.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.taulaNumeros.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.taulaNumeros.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.taulaNumeros.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.taulaNumeros.setAutoScroll(True)
        self.taulaNumeros.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.taulaNumeros.setTabKeyNavigation(False)
        self.taulaNumeros.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.taulaNumeros.setTextElideMode(QtCore.Qt.ElideLeft)
        self.taulaNumeros.setShowGrid(True)
        self.taulaNumeros.setGridStyle(QtCore.Qt.DotLine)
        self.taulaNumeros.setCornerButtonEnabled(True)
        self.taulaNumeros.setObjectName("taulaNumeros")
        self.taulaNumeros.setColumnCount(15)
        self.taulaNumeros.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.taulaNumeros.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.taulaNumeros.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.taulaNumeros.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.taulaNumeros.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.taulaNumeros.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.taulaNumeros.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.taulaNumeros.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.taulaNumeros.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.taulaNumeros.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.taulaNumeros.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.taulaNumeros.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.taulaNumeros.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.taulaNumeros.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.taulaNumeros.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.taulaNumeros.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.taulaNumeros.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.taulaNumeros.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.taulaNumeros.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.taulaNumeros.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.taulaNumeros.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.taulaNumeros.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.taulaNumeros.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(0, 7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(0, 8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(0, 9, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(0, 10, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(0, 11, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(0, 12, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(0, 13, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(0, 14, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(1, 6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(1, 7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(1, 8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(1, 9, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(1, 10, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(1, 11, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(1, 12, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(1, 13, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(1, 14, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(2, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(2, 6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(2, 7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(2, 8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(2, 9, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(2, 10, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(2, 11, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(2, 12, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(2, 13, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(2, 14, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(3, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(3, 6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(3, 7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(3, 8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(3, 9, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(3, 10, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(3, 11, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(3, 12, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(3, 13, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(3, 14, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(4, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(4, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(4, 6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(4, 7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(4, 8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(4, 9, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(4, 10, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(4, 11, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(4, 12, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(4, 13, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(4, 14, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(5, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(5, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(5, 6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(5, 7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(5, 8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.taulaNumeros.setItem(5, 9, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(5, 10, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(5, 11, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(5, 12, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(5, 13, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taulaNumeros.setItem(5, 14, item)
        self.taulaNumeros.horizontalHeader().setVisible(False)
        self.taulaNumeros.horizontalHeader().setDefaultSectionSize(100)
        self.taulaNumeros.horizontalHeader().setHighlightSections(True)
        self.taulaNumeros.horizontalHeader().setMinimumSectionSize(100)
        self.taulaNumeros.verticalHeader().setVisible(False)
        self.taulaNumeros.verticalHeader().setCascadingSectionResizes(False)
        self.taulaNumeros.verticalHeader().setDefaultSectionSize(64)
        self.taulaNumeros.verticalHeader().setMinimumSectionSize(64)
        self.horizontalLayout_2.addWidget(self.taulaNumeros)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 3)
        spacerItem9 = QtWidgets.QSpacerItem(20, 58, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem9, 3, 1, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem10)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ultimsNumeros = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.ultimsNumeros.setFont(font)
        self.ultimsNumeros.setObjectName("ultimsNumeros")
        self.verticalLayout_3.addWidget(self.ultimsNumeros)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ultim1 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.ultim1.setFont(font)
        self.ultim1.setAlignment(QtCore.Qt.AlignCenter)
        self.ultim1.setObjectName("ultim1")
        self.horizontalLayout_4.addWidget(self.ultim1)
        self.ultim2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.ultim2.setFont(font)
        self.ultim2.setAlignment(QtCore.Qt.AlignCenter)
        self.ultim2.setObjectName("ultim2")
        self.horizontalLayout_4.addWidget(self.ultim2)
        self.ultim3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.ultim3.setFont(font)
        self.ultim3.setAlignment(QtCore.Qt.AlignCenter)
        self.ultim3.setObjectName("ultim3")
        self.horizontalLayout_4.addWidget(self.ultim3)
        self.ultim4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.ultim4.setFont(font)
        self.ultim4.setAlignment(QtCore.Qt.AlignCenter)
        self.ultim4.setObjectName("ultim4")
        self.horizontalLayout_4.addWidget(self.ultim4)
        self.ultim5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.ultim5.setFont(font)
        self.ultim5.setAlignment(QtCore.Qt.AlignCenter)
        self.ultim5.setObjectName("ultim5")
        self.horizontalLayout_4.addWidget(self.ultim5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem11)
        self.reset = QtWidgets.QPushButton(self.centralwidget)
        self.reset.setMinimumSize(QtCore.QSize(200, 50))
        self.reset.setStyleSheet("background-color: rgb(239, 41, 41);\n"
"color: rgb(255, 255, 255);\n"
"border-color: rgb(164, 0, 0);")
        self.reset.setObjectName("reset")
        self.verticalLayout_2.addWidget(self.reset)
        self.horizontalLayout_7.addLayout(self.verticalLayout_2)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem12)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lectorNumero = QtWidgets.QLineEdit(self.centralwidget)
        self.lectorNumero.setMinimumSize(QtCore.QSize(200, 50))
        self.lectorNumero.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lectorNumero.setMaxLength(2)
        self.lectorNumero.setAlignment(QtCore.Qt.AlignCenter)
        self.lectorNumero.setClearButtonEnabled(False)
        self.lectorNumero.setObjectName("lectorNumero")
        self.horizontalLayout_6.addWidget(self.lectorNumero)
        self.botoNumero = QtWidgets.QPushButton(self.centralwidget)
        self.botoNumero.setMinimumSize(QtCore.QSize(200, 50))
        self.botoNumero.setObjectName("botoNumero")
        self.horizontalLayout_6.addWidget(self.botoNumero)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem13)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.linia = QtWidgets.QPushButton(self.centralwidget)
        self.linia.setMinimumSize(QtCore.QSize(200, 50))
        self.linia.setObjectName("linia")
        self.horizontalLayout_5.addWidget(self.linia)
        self.bingo = QtWidgets.QPushButton(self.centralwidget)
        self.bingo.setMinimumSize(QtCore.QSize(200, 50))
        self.bingo.setObjectName("bingo")
        self.horizontalLayout_5.addWidget(self.bingo)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7.addLayout(self.verticalLayout_4)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem14)
        self.gridLayout.addLayout(self.horizontalLayout_7, 4, 0, 1, 3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem15)
        self.developedBy = QtWidgets.QLabel(self.centralwidget)
        self.developedBy.setAlignment(QtCore.Qt.AlignCenter)
        self.developedBy.setObjectName("developedBy")
        self.horizontalLayout_3.addWidget(self.developedBy)
        self.gridLayout.addLayout(self.horizontalLayout_3, 5, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lectorNumero, self.reset)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Bingo Centre d\'Esplai Flor de Neu"))
        self.logo1.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/logo/logo.png\"/></p></body></html>"))
        self.bingoSopar.setText(_translate("MainWindow", "BINGO SOPAR DE LA FAM"))
        self.esplai.setText(_translate("MainWindow", "Centre d\'Esplai Flor de Neu"))
        self.logo2.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/logo/logo.png\"/></p></body></html>"))
        item = self.taulaNumeros.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "f1"))
        item = self.taulaNumeros.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "f2"))
        item = self.taulaNumeros.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "f3"))
        item = self.taulaNumeros.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "f4"))
        item = self.taulaNumeros.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "f5"))
        item = self.taulaNumeros.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "f6"))
        item = self.taulaNumeros.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "c1"))
        item = self.taulaNumeros.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "c2"))
        item = self.taulaNumeros.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "c3"))
        item = self.taulaNumeros.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "c4"))
        item = self.taulaNumeros.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "c5"))
        item = self.taulaNumeros.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "c6"))
        item = self.taulaNumeros.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "c7"))
        item = self.taulaNumeros.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "c8"))
        item = self.taulaNumeros.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "c9"))
        item = self.taulaNumeros.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "c10"))
        item = self.taulaNumeros.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "c11"))
        item = self.taulaNumeros.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "c12"))
        item = self.taulaNumeros.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "c13"))
        item = self.taulaNumeros.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "c14"))
        item = self.taulaNumeros.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "c15"))
        __sortingEnabled = self.taulaNumeros.isSortingEnabled()
        self.taulaNumeros.setSortingEnabled(False)
        item = self.taulaNumeros.item(0, 0)
        item.setText(_translate("MainWindow", "01"))
        item = self.taulaNumeros.item(0, 1)
        item.setText(_translate("MainWindow", "02"))
        item = self.taulaNumeros.item(0, 2)
        item.setText(_translate("MainWindow", "03"))
        item = self.taulaNumeros.item(0, 3)
        item.setText(_translate("MainWindow", "04"))
        item = self.taulaNumeros.item(0, 4)
        item.setText(_translate("MainWindow", "05"))
        item = self.taulaNumeros.item(0, 5)
        item.setText(_translate("MainWindow", "06"))
        item = self.taulaNumeros.item(0, 6)
        item.setText(_translate("MainWindow", "07"))
        item = self.taulaNumeros.item(0, 7)
        item.setText(_translate("MainWindow", "08"))
        item = self.taulaNumeros.item(0, 8)
        item.setText(_translate("MainWindow", "09"))
        item = self.taulaNumeros.item(0, 9)
        item.setText(_translate("MainWindow", "10"))
        item = self.taulaNumeros.item(0, 10)
        item.setText(_translate("MainWindow", "11"))
        item = self.taulaNumeros.item(0, 11)
        item.setText(_translate("MainWindow", "12"))
        item = self.taulaNumeros.item(0, 12)
        item.setText(_translate("MainWindow", "13"))
        item = self.taulaNumeros.item(0, 13)
        item.setText(_translate("MainWindow", "14"))
        item = self.taulaNumeros.item(0, 14)
        item.setText(_translate("MainWindow", "15"))
        item = self.taulaNumeros.item(1, 0)
        item.setText(_translate("MainWindow", "16"))
        item = self.taulaNumeros.item(1, 1)
        item.setText(_translate("MainWindow", "17"))
        item = self.taulaNumeros.item(1, 2)
        item.setText(_translate("MainWindow", "18"))
        item = self.taulaNumeros.item(1, 3)
        item.setText(_translate("MainWindow", "19"))
        item = self.taulaNumeros.item(1, 4)
        item.setText(_translate("MainWindow", "20"))
        item = self.taulaNumeros.item(1, 5)
        item.setText(_translate("MainWindow", "21"))
        item = self.taulaNumeros.item(1, 6)
        item.setText(_translate("MainWindow", "22"))
        item = self.taulaNumeros.item(1, 7)
        item.setText(_translate("MainWindow", "23"))
        item = self.taulaNumeros.item(1, 8)
        item.setText(_translate("MainWindow", "24"))
        item = self.taulaNumeros.item(1, 9)
        item.setText(_translate("MainWindow", "25"))
        item = self.taulaNumeros.item(1, 10)
        item.setText(_translate("MainWindow", "26"))
        item = self.taulaNumeros.item(1, 11)
        item.setText(_translate("MainWindow", "27"))
        item = self.taulaNumeros.item(1, 12)
        item.setText(_translate("MainWindow", "28"))
        item = self.taulaNumeros.item(1, 13)
        item.setText(_translate("MainWindow", "29"))
        item = self.taulaNumeros.item(1, 14)
        item.setText(_translate("MainWindow", "30"))
        item = self.taulaNumeros.item(2, 0)
        item.setText(_translate("MainWindow", "31"))
        item = self.taulaNumeros.item(2, 1)
        item.setText(_translate("MainWindow", "32"))
        item = self.taulaNumeros.item(2, 2)
        item.setText(_translate("MainWindow", "33"))
        item = self.taulaNumeros.item(2, 3)
        item.setText(_translate("MainWindow", "34"))
        item = self.taulaNumeros.item(2, 4)
        item.setText(_translate("MainWindow", "35"))
        item = self.taulaNumeros.item(2, 5)
        item.setText(_translate("MainWindow", "36"))
        item = self.taulaNumeros.item(2, 6)
        item.setText(_translate("MainWindow", "37"))
        item = self.taulaNumeros.item(2, 7)
        item.setText(_translate("MainWindow", "38"))
        item = self.taulaNumeros.item(2, 8)
        item.setText(_translate("MainWindow", "39"))
        item = self.taulaNumeros.item(2, 9)
        item.setText(_translate("MainWindow", "40"))
        item = self.taulaNumeros.item(2, 10)
        item.setText(_translate("MainWindow", "41"))
        item = self.taulaNumeros.item(2, 11)
        item.setText(_translate("MainWindow", "42"))
        item = self.taulaNumeros.item(2, 12)
        item.setText(_translate("MainWindow", "43"))
        item = self.taulaNumeros.item(2, 13)
        item.setText(_translate("MainWindow", "44"))
        item = self.taulaNumeros.item(2, 14)
        item.setText(_translate("MainWindow", "45"))
        item = self.taulaNumeros.item(3, 0)
        item.setText(_translate("MainWindow", "46"))
        item = self.taulaNumeros.item(3, 1)
        item.setText(_translate("MainWindow", "47"))
        item = self.taulaNumeros.item(3, 2)
        item.setText(_translate("MainWindow", "48"))
        item = self.taulaNumeros.item(3, 3)
        item.setText(_translate("MainWindow", "49"))
        item = self.taulaNumeros.item(3, 4)
        item.setText(_translate("MainWindow", "50"))
        item = self.taulaNumeros.item(3, 5)
        item.setText(_translate("MainWindow", "51"))
        item = self.taulaNumeros.item(3, 6)
        item.setText(_translate("MainWindow", "52"))
        item = self.taulaNumeros.item(3, 7)
        item.setText(_translate("MainWindow", "53"))
        item = self.taulaNumeros.item(3, 8)
        item.setText(_translate("MainWindow", "54"))
        item = self.taulaNumeros.item(3, 9)
        item.setText(_translate("MainWindow", "55"))
        item = self.taulaNumeros.item(3, 10)
        item.setText(_translate("MainWindow", "56"))
        item = self.taulaNumeros.item(3, 11)
        item.setText(_translate("MainWindow", "57"))
        item = self.taulaNumeros.item(3, 12)
        item.setText(_translate("MainWindow", "58"))
        item = self.taulaNumeros.item(3, 13)
        item.setText(_translate("MainWindow", "59"))
        item = self.taulaNumeros.item(3, 14)
        item.setText(_translate("MainWindow", "60"))
        item = self.taulaNumeros.item(4, 0)
        item.setText(_translate("MainWindow", "61"))
        item = self.taulaNumeros.item(4, 1)
        item.setText(_translate("MainWindow", "62"))
        item = self.taulaNumeros.item(4, 2)
        item.setText(_translate("MainWindow", "63"))
        item = self.taulaNumeros.item(4, 3)
        item.setText(_translate("MainWindow", "64"))
        item = self.taulaNumeros.item(4, 4)
        item.setText(_translate("MainWindow", "65"))
        item = self.taulaNumeros.item(4, 5)
        item.setText(_translate("MainWindow", "66"))
        item = self.taulaNumeros.item(4, 6)
        item.setText(_translate("MainWindow", "67"))
        item = self.taulaNumeros.item(4, 7)
        item.setText(_translate("MainWindow", "68"))
        item = self.taulaNumeros.item(4, 8)
        item.setText(_translate("MainWindow", "69"))
        item = self.taulaNumeros.item(4, 9)
        item.setText(_translate("MainWindow", "70"))
        item = self.taulaNumeros.item(4, 10)
        item.setText(_translate("MainWindow", "71"))
        item = self.taulaNumeros.item(4, 11)
        item.setText(_translate("MainWindow", "72"))
        item = self.taulaNumeros.item(4, 12)
        item.setText(_translate("MainWindow", "73"))
        item = self.taulaNumeros.item(4, 13)
        item.setText(_translate("MainWindow", "74"))
        item = self.taulaNumeros.item(4, 14)
        item.setText(_translate("MainWindow", "75"))
        item = self.taulaNumeros.item(5, 0)
        item.setText(_translate("MainWindow", "76"))
        item = self.taulaNumeros.item(5, 1)
        item.setText(_translate("MainWindow", "77"))
        item = self.taulaNumeros.item(5, 2)
        item.setText(_translate("MainWindow", "78"))
        item = self.taulaNumeros.item(5, 3)
        item.setText(_translate("MainWindow", "79"))
        item = self.taulaNumeros.item(5, 4)
        item.setText(_translate("MainWindow", "80"))
        item = self.taulaNumeros.item(5, 5)
        item.setText(_translate("MainWindow", "81"))
        item = self.taulaNumeros.item(5, 6)
        item.setText(_translate("MainWindow", "82"))
        item = self.taulaNumeros.item(5, 7)
        item.setText(_translate("MainWindow", "83"))
        item = self.taulaNumeros.item(5, 8)
        item.setText(_translate("MainWindow", "84"))
        item = self.taulaNumeros.item(5, 9)
        item.setText(_translate("MainWindow", "85"))
        item = self.taulaNumeros.item(5, 10)
        item.setText(_translate("MainWindow", "86"))
        item = self.taulaNumeros.item(5, 11)
        item.setText(_translate("MainWindow", "87"))
        item = self.taulaNumeros.item(5, 12)
        item.setText(_translate("MainWindow", "88"))
        item = self.taulaNumeros.item(5, 13)
        item.setText(_translate("MainWindow", "89"))
        item = self.taulaNumeros.item(5, 14)
        item.setText(_translate("MainWindow", "90"))
        self.taulaNumeros.setSortingEnabled(__sortingEnabled)
        self.ultimsNumeros.setText(_translate("MainWindow", "Últims 5 números"))
        self.ultim1.setText(_translate("MainWindow", "-"))
        self.ultim2.setText(_translate("MainWindow", "-"))
        self.ultim3.setText(_translate("MainWindow", "-"))
        self.ultim4.setText(_translate("MainWindow", "-"))
        self.ultim5.setText(_translate("MainWindow", "-"))
        self.reset.setText(_translate("MainWindow", "&Reiniciar Partida"))
        self.lectorNumero.setPlaceholderText(_translate("MainWindow", "Número"))
        self.botoNumero.setText(_translate("MainWindow", "&Introduïr"))
        self.linia.setText(_translate("MainWindow", "&Línia"))
        self.bingo.setText(_translate("MainWindow", "&Bingo"))
        self.developedBy.setText(_translate("MainWindow", "by Pau Antonio Soler"))
import icona_rc
import logo_rc
